name: Integration

on: [ pull_request ]

permissions:
  contents: write

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: false
          dependency-graph: generate-and-submit

      - name: Build
        run: ./gradlew build --no-daemon
  dependency-review:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Perform dependency review
        uses: actions/dependency-review-action@v3
